# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

## find all the fibonacci sequence numbers 0 to 4 million. then find the even ones. then add those together = solution

module Problem2

  def self.fib(limit)
    #create an array, then puts stuff into the array, and pushes that number onto the end of the array
    arr = [] # create an empty array
    a,b = 0,1 # puts stuff in the array
  
  	while a < limit #while the number is under the limit
      arr << a # pushes a onto the end of the array
      a, b = b, a + b #sets the recurrsion formula
    end

    sum = arr.select { |i| i.even? }.reduce(:+) #the sum is the array, where you then select only the even numbers and add them together
  	
  end

  fib(4000000) #sets the limit
end