# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
# the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

## find all the fibonacci sequence numbers 0 to 4 million. then find the even ones. then add those together = solution

class Problem2

  def fib
  	a, b, sum = 1,2,3
  	while b < 4000000
  		sum += b if b.even?
  		a, b = b, a + b 
  	end
  	puts sum
  end
end